version: '3'

services:
  upload-webapp:
    build:
      context: ./upload-webapp
    ports:
      - "3000:3000"
    depends_on:
      - auth-svc
    networks:
      - bridge-net
  auth-svc:
    build:
      context: ./auth-svc
    ports:
      - "8000:8000"
    networks:
      - bridge-net
  database:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: video_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks: 
      - bridge-net


networks:
  bridge-net:
    driver: bridge