services:
  upload-webapp:
    build:
      context: ./upload-webapp
    ports:
      - "3000:3000"
    depends_on:
      - auth-svc
      - file-svc
    volumes:
      - myapp-temp:/usr/src/app/temp
    networks:
      - bridge-net
  
  auth-svc:
    build:
      context: ./auth-svc
    ports:
      - "8000:8000"
    networks:
      - bridge-net
  
  file-svc:
    build:
      context: ./file-svc
    ports:
      - "4000:4000"
    volumes:
      - myapp-temp:/usr/src/app/temp
    networks:
      - bridge-net
  
  database:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: video_db
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
    volumes:
      - db-data:/var/lib/mysql
      - db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks: 
      - bridge-net

networks:
  bridge-net:
    driver: bridge

volumes:
  myapp-temp:
    external: false
  db-data:
    external: false
  db-init:
