services:
  upload-webapp:
    build:
      context: ./upload-webapp
    ports:
      - "3000:3000"
    depends_on:
      - auth-svc
      - file-svc
    volumes:
      - myapp-temp:/usr/src/app/temp
    networks:
      - bridge-net
    env_file:
      - .env

  auth-svc:
    build:
      context: ./auth-svc
    ports:
      - "8000:8000"
    networks:
      - bridge-net
    env_file:
      - .env

  file-svc:
    build:
      context: ./file-svc
    ports:
      - "4000:4000"
    volumes:
      - myapp-temp:/usr/src/app/temp
    networks:
      - bridge-net
    env_file:
      - .env

  streaming-svc:
    build:
      context: ./streaming-webapp
    ports:
      - "3100:3100"
    depends_on:
      - auth-svc
      - file-svc
    networks:
      - bridge-net
    env_file:
      - .env

  database:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: video_db
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge

volumes:
  myapp-temp:
    external: false
  mariadb_data:
