apiVersion: v1
kind: ConfigMap
metadata:
  name: database-init-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS videos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        video_name VARCHAR(255) NOT NULL,
        video_path VARCHAR(255) NOT NULL
    );
