apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-svc
spec:
  selector:
    matchLabels:
      app: streaming-svc
  template:
    metadata:
      labels:
        app: streaming-svc
    spec:
      containers:
      - name: streaming-svc
        image: enderso/streaming-webapp:latest
        ports:
        - containerPort: 3100
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASS
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: DB_USER
