apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-webapp
spec:
  selector:
    matchLabels:
      app: upload-webapp
  template:
    metadata:
      labels:
        app: upload-webapp
    spec:
      containers:
      - name: upload-webapp
        image: enderso/upload-webapp:latest
        ports:
        - containerPort: 3000
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASS
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: DB_USER
          - name: S3_BUCKET           
            valueFrom:
              configMapKeyRef:
                name: app-configmap  
                key: S3_BUCKET
        volumeMounts:
        - name: storage-temp-pv
          mountPath: /usr/src/app/temp
      volumes:
        - name: storage-temp-pv
          persistentVolumeClaim:
            claimName: storage-temp-pvc
